"""add api_keys and external_files tables

Revision ID: b3e935e5086c
Revises: 011_update_tool_slug_storybook
Create Date: 2026-05-25 18:41:22.546394

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b3e935e5086c'
down_revision = '011_update_tool_slug_storybook'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='密钥名称'),
    sa.Column('key_prefix', sa.String(length=10), nullable=False, comment='密钥前缀，用于列表脱敏显示'),
    sa.Column('key_hash', sa.String(length=128), nullable=False, comment='SHA-256哈希'),
    sa.Column('key_encrypted', sa.Text(), nullable=False, comment='AES-256加密的密钥明文'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='active/disabled'),
    sa.Column('last_used_at', sa.Integer(), nullable=True, comment='最后使用时间戳'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('external_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('api_endpoint', sa.String(length=50), nullable=False, comment='images/audio/video/chat'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_files_id'), 'external_files', ['id'], unique=False)
    op.create_index(op.f('ix_external_files_user_id'), 'external_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_files_user_id'), table_name='external_files')
    op.drop_index(op.f('ix_external_files_id'), table_name='external_files')
    op.drop_table('external_files')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
