"""Add missing fields to point_transactions and other tables

Revision ID: cb73fdd10709
Revises: 005
Create Date: 2026-05-20 18:14:25.742977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = 'cb73fdd10709'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum types (add REWARD to match existing data)
    point_transaction_type = sa.Enum('RECHARGE', 'CONSUME', 'REFUND', 'ADJUST', 'FREEZE', 'UNFREEZE', 'REWARD', name='pointtransactiontype')
    point_transaction_type.create(op.get_bind(), checkfirst=True)
    op.create_table('recharge_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='档位名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='档位描述'),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='原价(元)'),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='售价(元)'),
    sa.Column('base_points', sa.Integer(), nullable=False, comment='基础积分'),
    sa.Column('bonus_points', sa.Integer(), nullable=False, comment='赠送积分'),
    sa.Column('bonus_percentage', sa.Integer(), nullable=False, comment='赠送比例(0-100)'),
    sa.Column('is_popular', sa.Boolean(), nullable=False, comment='是否热门推荐'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序，数字越小越靠前'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_package_is_active', 'recharge_packages', ['is_active'], unique=False)
    op.create_index('idx_package_sort_order', 'recharge_packages', ['sort_order'], unique=False)
    op.create_index(op.f('ix_recharge_packages_id'), 'recharge_packages', ['id'], unique=False)
    op.create_table('tool_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='分类标识'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='分类图标URL'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='分类描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序，数字越小越靠前'),
    sa.Column('tool_count', sa.Integer(), nullable=False, comment='工具数量'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='是否推荐'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父分类ID'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['tool_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_parent_id', 'tool_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tool_categories_id'), 'tool_categories', ['id'], unique=False)
    op.create_index(op.f('ix_tool_categories_name'), 'tool_categories', ['name'], unique=True)
    op.create_index(op.f('ix_tool_categories_parent_id'), 'tool_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tool_categories_slug'), 'tool_categories', ['slug'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='日志ID'),
    sa.Column('admin_id', sa.UUID(), nullable=True, comment='管理员ID'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='目标类型'),
    sa.Column('target_id', sa.String(length=100), nullable=True, comment='目标ID'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('request_data', JSONB(), nullable=True, comment='请求数据(JSON)'),
    sa.Column('response_data', JSONB(), nullable=True, comment='响应数据(JSON)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='是否成功'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_admin_action', 'admin_audit_logs', ['admin_id', 'action_type'], unique=False)
    op.create_index('idx_audit_created_at', 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_target', 'admin_audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_action_type'), 'admin_audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_success'), 'admin_audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_id'), 'admin_audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_type'), 'admin_audit_logs', ['target_type'], unique=False)
    op.create_table('idea_submissions',
    sa.Column('id', sa.UUID(), nullable=False, comment='创意ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='提交用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='创意标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='创意描述'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图片URL'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签(JSON数组格式)'),
    sa.Column('contact_info', sa.String(length=200), nullable=True, comment='联系方式'),
    sa.Column('vote_count', sa.Integer(), nullable=False, comment='投票数'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览数'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending待审核 reviewing审核中 approved已通过 implemented已实现 rejected已拒绝'),
    sa.Column('admin_remark', sa.String(length=500), nullable=True, comment='管理员备注'),
    sa.Column('admin_id', sa.UUID(), nullable=True, comment='审核管理员ID'),
    sa.Column('reviewed_at', sa.Integer(), nullable=True, comment='审核时间'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_idea_category_status', 'idea_submissions', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_idea_submissions_admin_id'), 'idea_submissions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_idea_submissions_category'), 'idea_submissions', ['category'], unique=False)
    op.create_index(op.f('ix_idea_submissions_id'), 'idea_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_idea_submissions_status'), 'idea_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_idea_submissions_user_id'), 'idea_submissions', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('order_no', sa.String(length=64), nullable=False, comment='订单号'),
    sa.Column('third_party_order_no', sa.String(length=128), nullable=True, comment='第三方支付订单号'),
    sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='支付金额(元)'),
    sa.Column('base_points', sa.Integer(), nullable=False, comment='基础积分'),
    sa.Column('bonus_points', sa.Integer(), nullable=False, comment='赠送积分'),
    sa.Column('total_points', sa.Integer(), nullable=False, comment='总积分(基础+赠送)'),
    sa.Column('payment_provider', sa.Enum('WECHAT', 'ALIPAY', 'SIMULATED', name='paymentprovider'), nullable=False, comment='支付提供商'),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'EXPIRED', name='orderstatus'), nullable=False, comment='订单状态'),
    sa.Column('paid_at', sa.Integer(), nullable=True, comment='支付时间'),
    sa.Column('expired_at', sa.Integer(), nullable=True, comment='过期时间'),
    sa.Column('client_ip', sa.String(length=50), nullable=True, comment='客户端IP'),
    sa.Column('device_info', sa.String(length=255), nullable=True, comment='设备信息'),
    sa.Column('callback_raw', JSONB(), nullable=True, comment='支付回调原始数据(JSON)'),
    sa.Column('reconciliation_status', sa.Enum('PENDING', 'MATCHED', 'MISMATCHED', name='reconciliationstatus'), nullable=False, comment='对账状态'),
    sa.Column('reconciled_at', sa.Integer(), nullable=True, comment='对账时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.create_index('idx_order_user_id', 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_third_party_order_no'), 'orders', ['third_party_order_no'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('real_name_verifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('id_card_name', sa.String(length=50), nullable=False, comment='身份证姓名'),
    sa.Column('id_card_number_encrypted', sa.String(length=255), nullable=False, comment='身份证号(AES-256加密)'),
    sa.Column('id_card_hash', sa.String(length=64), nullable=False, comment='身份证号SHA-256哈希'),
    sa.Column('front_image', sa.String(length=255), nullable=True, comment='身份证正面照片URL'),
    sa.Column('back_image', sa.String(length=255), nullable=True, comment='身份证背面照片URL'),
    sa.Column('hold_image', sa.String(length=255), nullable=True, comment='手持身份证照片URL'),
    sa.Column('verification_status', sa.String(length=20), nullable=False, comment='审核状态：pending待提交 reviewing审核中 approved已通过 rejected已拒绝'),
    sa.Column('review_remark', sa.String(length=500), nullable=True, comment='审核备注'),
    sa.Column('reviewer_id', sa.UUID(), nullable=True, comment='审核人ID'),
    sa.Column('reviewed_at', sa.Integer(), nullable=True, comment='审核时间'),
    sa.Column('submitted_at', sa.Integer(), nullable=True, comment='提交时间'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_real_name_user_status', 'real_name_verifications', ['user_id', 'verification_status'], unique=False)
    op.create_index(op.f('ix_real_name_verifications_id'), 'real_name_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_real_name_verifications_id_card_hash'), 'real_name_verifications', ['id_card_hash'], unique=False)
    op.create_index(op.f('ix_real_name_verifications_reviewer_id'), 'real_name_verifications', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_real_name_verifications_user_id'), 'real_name_verifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_real_name_verifications_verification_status'), 'real_name_verifications', ['verification_status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('tool_id', sa.UUID(), nullable=True, comment='工具ID'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending待处理 running运行中 completed已完成 failed失败 cancelled已取消 timeout超时'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度0-100'),
    sa.Column('progress_message', sa.String(length=255), nullable=True, comment='进度消息'),
    sa.Column('snapshot_data', JSONB(), nullable=True, comment='快照数据用于断点续跑'),
    sa.Column('input_params', JSONB(), nullable=True, comment='输入参数'),
    sa.Column('result_preview', sa.Text(), nullable=True, comment='结果预览'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('estimated_cost', sa.Integer(), nullable=True, comment='预估费用'),
    sa.Column('actual_cost', sa.Integer(), nullable=True, comment='实际费用'),
    sa.Column('started_at', sa.Integer(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.Integer(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_tool_id'), 'tasks', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='工具标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('short_desc', sa.String(length=255), nullable=True, comment='简短描述'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图片URL'),
    sa.Column('category_id', sa.UUID(), nullable=True, comment='分类ID'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类名称（冗余字段）'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签列表，JSON格式'),
    sa.Column('base_fee', sa.Integer(), nullable=False, comment='基础费（积分）'),
    sa.Column('image_fee', sa.Integer(), nullable=False, comment='图片费（积分/张）'),
    sa.Column('audio_fee', sa.Integer(), nullable=False, comment='音频费（积分/分钟）'),
    sa.Column('token_fee', sa.Integer(), nullable=False, comment='Token费（积分/千token）'),
    sa.Column('config', JSONB(), nullable=True, comment='工具配置，JSON格式'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态：0下线 1上线 2维护中'),
    sa.Column('use_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('favorite_count', sa.Integer(), nullable=False, comment='收藏次数'),
    sa.Column('rating_count', sa.Integer(), nullable=False, comment='评价次数'),
    sa.Column('rating_avg', sa.Numeric(precision=2, scale=1), nullable=False, comment='平均评分'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['tool_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_category_id', 'tools', ['category_id'], unique=False)
    op.create_index('idx_tool_status', 'tools', ['status'], unique=False)
    op.create_index(op.f('ix_tools_category_id'), 'tools', ['category_id'], unique=False)
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_index(op.f('ix_tools_slug'), 'tools', ['slug'], unique=True)
    op.create_table('idea_votes',
    sa.Column('id', sa.UUID(), nullable=False, comment='投票ID'),
    sa.Column('idea_id', sa.UUID(), nullable=False, comment='创意ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('vote_type', sa.String(length=10), nullable=False, comment='投票类型：up支持 down反对'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id', 'user_id', name='uq_idea_user_vote')
    )
    op.create_index('idx_idea_vote_type', 'idea_votes', ['idea_id', 'vote_type'], unique=False)
    op.create_index(op.f('ix_idea_votes_id'), 'idea_votes', ['id'], unique=False)
    op.create_index(op.f('ix_idea_votes_idea_id'), 'idea_votes', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_votes_user_id'), 'idea_votes', ['user_id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='任务ID'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='日志级别：debug info warn error'),
    sa.Column('message', sa.Text(), nullable=False, comment='日志消息'),
    sa.Column('details', JSONB(), nullable=True, comment='详细信息'),
    sa.Column('timestamp', sa.Integer(), nullable=False, comment='时间戳'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_id'), 'task_logs', ['id'], unique=False)
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    op.create_table('tool_demos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False, comment='工具ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='案例标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='案例描述'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='案例封面图'),
    sa.Column('demo_type', sa.String(length=50), nullable=False, comment='案例类型：image/image_audio/video'),
    sa.Column('demo_images', sa.Text(), nullable=True, comment='演示图片，JSON数组格式'),
    sa.Column('input_params', JSONB(), nullable=True, comment='输入参数示例，JSON格式'),
    sa.Column('result_sample', JSONB(), nullable=True, comment='输出结果示例，JSON格式'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_demo_sort_order', 'tool_demos', ['sort_order'], unique=False)
    op.create_index('idx_demo_tool_id', 'tool_demos', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_demos_id'), 'tool_demos', ['id'], unique=False)
    op.create_index(op.f('ix_tool_demos_tool_id'), 'tool_demos', ['tool_id'], unique=False)
    op.create_table('tool_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('tool_id', sa.UUID(), nullable=False, comment='工具ID'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_favorite_user_tool', 'tool_favorites', ['user_id', 'tool_id'], unique=True)
    op.create_index(op.f('ix_tool_favorites_id'), 'tool_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_tool_favorites_tool_id'), 'tool_favorites', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_favorites_user_id'), 'tool_favorites', ['user_id'], unique=False)
    op.create_table('tool_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('tool_id', sa.UUID(), nullable=False, comment='工具ID'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='任务ID'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分：1-5星'),
    sa.Column('content', sa.Text(), nullable=True, comment='评价内容'),
    sa.Column('images', sa.Text(), nullable=True, comment='评价图片，JSON数组格式'),
    sa.Column('is_useful_count', sa.Integer(), nullable=False, comment='有用次数'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态：0隐藏 1显示'),
    sa.Column('admin_reply', sa.Text(), nullable=True, comment='管理员回复'),
    sa.Column('replied_at', sa.Integer(), nullable=True, comment='回复时间'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rating_tool_id', 'tool_ratings', ['tool_id'], unique=False)
    op.create_index('idx_rating_user_id', 'tool_ratings', ['user_id'], unique=False)
    op.create_index(op.f('ix_tool_ratings_id'), 'tool_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_tool_ratings_task_id'), 'tool_ratings', ['task_id'], unique=True)
    op.create_index(op.f('ix_tool_ratings_tool_id'), 'tool_ratings', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_ratings_user_id'), 'tool_ratings', ['user_id'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='任务ID'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父成果ID，用于迭代版本'),
    sa.Column('tool_id', sa.UUID(), nullable=True, comment='工具ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图片URL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：draft草稿 published已发布 archived已归档'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='查看次数'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞次数'),
    sa.Column('share_count', sa.Integer(), nullable=False, comment='分享次数'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['works.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_index(op.f('ix_works_parent_id'), 'works', ['parent_id'], unique=False)
    op.create_index(op.f('ix_works_task_id'), 'works', ['task_id'], unique=False)
    op.create_index(op.f('ix_works_tool_id'), 'works', ['tool_id'], unique=False)
    op.create_index(op.f('ix_works_user_id'), 'works', ['user_id'], unique=False)
    op.create_table('work_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.UUID(), nullable=False, comment='成果ID'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型：image图片 audio音频 video视频 pdf文档 psd源文件 other其他'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_url', sa.String(length=255), nullable=False, comment='文件URL'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('page_number', sa.Integer(), nullable=True, comment='页码'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='时长（秒，用于音频视频）'),
    sa.Column('is_preview', sa.Boolean(), nullable=False, comment='是否为预览文件'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_files_id'), 'work_files', ['id'], unique=False)
    op.create_index(op.f('ix_work_files_work_id'), 'work_files', ['work_id'], unique=False)
    op.create_table('work_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.UUID(), nullable=False, comment='成果ID'),
    sa.Column('share_type', sa.String(length=20), nullable=False, comment='分享类型：public公开 link链接 friends好友'),
    sa.Column('share_url', sa.String(length=255), nullable=True, comment='分享链接'),
    sa.Column('password', sa.String(length=50), nullable=True, comment='分享密码'),
    sa.Column('expire_at', sa.Integer(), nullable=True, comment='过期时间'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='查看次数'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞次数'),
    sa.Column('comment_count', sa.Integer(), nullable=False, comment='评论次数'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending待审核 approved已通过 rejected已拒绝'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='审核人ID'),
    sa.Column('reviewed_at', sa.Integer(), nullable=True, comment='审核时间'),
    sa.Column('created_at', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_shares_id'), 'work_shares', ['id'], unique=False)
    op.create_index(op.f('ix_work_shares_work_id'), 'work_shares', ['work_id'], unique=False)
    op.add_column('point_transactions', sa.Column('related_type', sa.String(length=50), nullable=True, comment='关联类型（order/task等）'))
    op.add_column('point_transactions', sa.Column('idempotency_key', sa.String(length=128), nullable=True, comment='幂等键，用于防止重复交易'))
    op.add_column('point_transactions', sa.Column('balance_before', sa.Integer(), nullable=True, server_default='0', comment='变更前余额'))
    op.add_column('point_transactions', sa.Column('balance_after', sa.Integer(), nullable=True, server_default='0', comment='变更后余额'))
    op.add_column('point_transactions', sa.Column('operator', sa.String(length=100), nullable=True, comment='操作者（系统或管理员ID）'))
    op.add_column('point_transactions', sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'))
    op.add_column('point_transactions', sa.Column('order_id', sa.UUID(), nullable=True, comment='关联订单ID'))
    # Convert lowercase strings to uppercase enum values
    op.execute('ALTER TABLE point_transactions ALTER COLUMN type TYPE pointtransactiontype USING upper(type)::pointtransactiontype')
    op.alter_column('point_transactions', 'type',
               existing_type=sa.Enum('RECHARGE', 'CONSUME', 'REFUND', 'ADJUST', 'FREEZE', 'UNFREEZE', 'REWARD', name='pointtransactiontype'),
               comment='交易类型',
               existing_comment='类型：recharge充值 consume消费 refund退款 adjust调整',
               existing_nullable=False)
    op.create_index('idx_transaction_created_at', 'point_transactions', ['created_at'], unique=False)
    op.create_index('idx_transaction_related', 'point_transactions', ['related_id', 'related_type'], unique=False)
    op.create_index('idx_transaction_type', 'point_transactions', ['type'], unique=False)
    op.create_index('idx_transaction_user_id', 'point_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_point_transactions_idempotency_key'), 'point_transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_point_transactions_order_id'), 'point_transactions', ['order_id'], unique=False)
    op.create_foreign_key(None, 'point_transactions', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'point_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_point_transactions_order_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_idempotency_key'), table_name='point_transactions')
    op.drop_index('idx_transaction_user_id', table_name='point_transactions')
    op.drop_index('idx_transaction_type', table_name='point_transactions')
    op.drop_index('idx_transaction_related', table_name='point_transactions')
    op.drop_index('idx_transaction_created_at', table_name='point_transactions')
    op.alter_column('point_transactions', 'type',
               existing_type=sa.Enum('RECHARGE', 'CONSUME', 'REFUND', 'ADJUST', 'FREEZE', 'UNFREEZE', 'REWARD', name='pointtransactiontype'),
               type_=sa.VARCHAR(length=20),
               comment='类型：recharge充值 consume消费 refund退款 adjust调整',
               existing_comment='交易类型',
               existing_nullable=False)
    op.drop_column('point_transactions', 'order_id')
    op.drop_column('point_transactions', 'remark')
    op.drop_column('point_transactions', 'operator')
    op.drop_column('point_transactions', 'balance_after')
    op.drop_column('point_transactions', 'balance_before')
    op.drop_column('point_transactions', 'idempotency_key')
    op.drop_column('point_transactions', 'related_type')
    op.drop_index(op.f('ix_work_shares_work_id'), table_name='work_shares')
    op.drop_index(op.f('ix_work_shares_id'), table_name='work_shares')
    op.drop_table('work_shares')
    op.drop_index(op.f('ix_work_files_work_id'), table_name='work_files')
    op.drop_index(op.f('ix_work_files_id'), table_name='work_files')
    op.drop_table('work_files')
    op.drop_index(op.f('ix_works_user_id'), table_name='works')
    op.drop_index(op.f('ix_works_tool_id'), table_name='works')
    op.drop_index(op.f('ix_works_task_id'), table_name='works')
    op.drop_index(op.f('ix_works_parent_id'), table_name='works')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_tool_ratings_user_id'), table_name='tool_ratings')
    op.drop_index(op.f('ix_tool_ratings_tool_id'), table_name='tool_ratings')
    op.drop_index(op.f('ix_tool_ratings_task_id'), table_name='tool_ratings')
    op.drop_index(op.f('ix_tool_ratings_id'), table_name='tool_ratings')
    op.drop_index('idx_rating_user_id', table_name='tool_ratings')
    op.drop_index('idx_rating_tool_id', table_name='tool_ratings')
    op.drop_table('tool_ratings')
    op.drop_index(op.f('ix_tool_favorites_user_id'), table_name='tool_favorites')
    op.drop_index(op.f('ix_tool_favorites_tool_id'), table_name='tool_favorites')
    op.drop_index(op.f('ix_tool_favorites_id'), table_name='tool_favorites')
    op.drop_index('idx_favorite_user_tool', table_name='tool_favorites')
    op.drop_table('tool_favorites')
    op.drop_index(op.f('ix_tool_demos_tool_id'), table_name='tool_demos')
    op.drop_index(op.f('ix_tool_demos_id'), table_name='tool_demos')
    op.drop_index('idx_demo_tool_id', table_name='tool_demos')
    op.drop_index('idx_demo_sort_order', table_name='tool_demos')
    op.drop_table('tool_demos')
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_idea_votes_user_id'), table_name='idea_votes')
    op.drop_index(op.f('ix_idea_votes_idea_id'), table_name='idea_votes')
    op.drop_index(op.f('ix_idea_votes_id'), table_name='idea_votes')
    op.drop_index('idx_idea_vote_type', table_name='idea_votes')
    op.drop_table('idea_votes')
    op.drop_index(op.f('ix_tools_slug'), table_name='tools')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_category_id'), table_name='tools')
    op.drop_index('idx_tool_status', table_name='tools')
    op.drop_index('idx_tool_category_id', table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_tool_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_real_name_verifications_verification_status'), table_name='real_name_verifications')
    op.drop_index(op.f('ix_real_name_verifications_user_id'), table_name='real_name_verifications')
    op.drop_index(op.f('ix_real_name_verifications_reviewer_id'), table_name='real_name_verifications')
    op.drop_index(op.f('ix_real_name_verifications_id_card_hash'), table_name='real_name_verifications')
    op.drop_index(op.f('ix_real_name_verifications_id'), table_name='real_name_verifications')
    op.drop_index('idx_real_name_user_status', table_name='real_name_verifications')
    op.drop_table('real_name_verifications')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_third_party_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('idx_order_user_id', table_name='orders')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_index('idx_order_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_idea_submissions_user_id'), table_name='idea_submissions')
    op.drop_index(op.f('ix_idea_submissions_status'), table_name='idea_submissions')
    op.drop_index(op.f('ix_idea_submissions_id'), table_name='idea_submissions')
    op.drop_index(op.f('ix_idea_submissions_category'), table_name='idea_submissions')
    op.drop_index(op.f('ix_idea_submissions_admin_id'), table_name='idea_submissions')
    op.drop_index('idx_idea_category_status', table_name='idea_submissions')
    op.drop_table('idea_submissions')
    op.drop_index(op.f('ix_admin_audit_logs_target_type'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_target_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_success'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action_type'), table_name='admin_audit_logs')
    op.drop_index('idx_audit_target', table_name='admin_audit_logs')
    op.drop_index('idx_audit_created_at', table_name='admin_audit_logs')
    op.drop_index('idx_audit_admin_action', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_tool_categories_slug'), table_name='tool_categories')
    op.drop_index(op.f('ix_tool_categories_parent_id'), table_name='tool_categories')
    op.drop_index(op.f('ix_tool_categories_name'), table_name='tool_categories')
    op.drop_index(op.f('ix_tool_categories_id'), table_name='tool_categories')
    op.drop_index('idx_category_parent_id', table_name='tool_categories')
    op.drop_table('tool_categories')
    op.drop_index(op.f('ix_recharge_packages_id'), table_name='recharge_packages')
    op.drop_index('idx_package_sort_order', table_name='recharge_packages')
    op.drop_index('idx_package_is_active', table_name='recharge_packages')
    op.drop_table('recharge_packages')
    # ### end Alembic commands ###
