"""add param_schema to tools

Revision ID: dd91312939e6
Revises: b3e935e5086c
Create Date: 2026-05-27 11:32:49.314798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd91312939e6'
down_revision = 'b3e935e5086c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedbacks_status'), 'feedbacks', ['status'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.alter_column('point_transactions', 'balance_before',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='变更前余额',
               existing_server_default=sa.text('0'))
    op.alter_column('point_transactions', 'balance_after',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='变更后余额',
               existing_server_default=sa.text('0'))
    op.add_column('tools', sa.Column('param_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='参数字段映射，JSON数组：[{key, label, type, order}]'))
    op.alter_column('tools', 'cover_image',
               existing_type=sa.TEXT(),
               comment='封面图片URL，多张图片以 | 分隔',
               existing_comment='封面图片URL',
               existing_nullable=True)
    op.alter_column('tools', 'audio_fee',
               existing_type=sa.INTEGER(),
               comment='音频费（积分/段）',
               existing_comment='音频费（积分/分钟）',
               existing_nullable=False)
    op.alter_column('tools', 'usage_modes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='使用模式，JSON数组：["form", "dialog"]',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'usage_modes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='使用模式，JSON数组：["form", "dialog"]',
               existing_nullable=True)
    op.alter_column('tools', 'audio_fee',
               existing_type=sa.INTEGER(),
               comment='音频费（积分/分钟）',
               existing_comment='音频费（积分/段）',
               existing_nullable=False)
    op.alter_column('tools', 'cover_image',
               existing_type=sa.TEXT(),
               comment='封面图片URL',
               existing_comment='封面图片URL，多张图片以 | 分隔',
               existing_nullable=True)
    op.drop_column('tools', 'param_schema')
    op.alter_column('point_transactions', 'balance_after',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='变更后余额',
               existing_server_default=sa.text('0'))
    op.alter_column('point_transactions', 'balance_before',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='变更前余额',
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_status'), table_name='feedbacks')
    # ### end Alembic commands ###
